### ISSUE TITLE
Removal of items after 23:59:00

### ISSUE THREAD

**Issue by Godje** [joshavanier/qyllium#1]
I usually work at night and write down some things I can forget later.
As soon as time crosses to the next day, everything is fine. But if I click on any of tasks that I completed, it will remove all of the items and start anew. The item that I completed doesn't stay either.

**Comment by joshavanier** [comment]
Press <kbd>Tab</kbd> to expand Qyllium. This will show you all your existing tasks, events, and notes. I'll add a button to toggle this

**Comment by Godje** [comment]
I am running i3-gaps. Since my Qyllium window is a tiled window, not a
floating window, it won't expand on it's own, unless I resize it manually.
But to make my rice look nice my Qyllium window is thin, to look like a
todo list (which it is). And when I press tab all I see is a visual
glitches for 2ms and comeback to normal. I guess, it is not your fault that
I use i3-gaps. It's just that I didn't want my previous todo's to
disappear, since my habit is to do things overnight.


2018-01-21 17:58 GMT-08:00 Josh Avanier <notifications@github.com>:

**Comment by joshavanier** [comment]
I use i3-gaps as well: `for_window [class="Qyllium"] floating enable`

**Comment by Godje** [comment]
That's a good idea, but that will kind of mess with the nice workflow I got. Not that you suppose to care about it, anyways. Is there a way I can build from source, to disable the disappearing items?
