### ISSUE TITLE
Build a 64-bit version, please

### ISSUE THREAD

**Issue by Godje** [joshavanier/qyllium#2]
Every time I try to launch I am missing a package.

While installing the package, another dependency is showing up. And more, and more, and more and more. In the end, I installed exactly 167 packages to run the Electron app.

Is there a way I can build a 64-bit version myself if that is a struggle to release it?

**Comment by joshavanier** [comment]
Oh the 64-bit should have been included on itch.io by default (I run a script to manage builds). I think it was accidentally deleted when I was doing some reorganising the other day. Check again in a few minutes; I'm re-uploading it now

And just to answer your question about building it on your own:
`electron-packager {sourceFolder} Qyllium --platform=linux --arch=x64`
